CREATE TABLE TBL_MEMBER(
	member_name varchar2(1000),
	member_AGE NUMBER
);

CREATE TABLE TBL_STUDENT(
   STUDENT_NUMBER NUMBER,
   STUDENT_NAME VARCHAR2(1000),
   STUDENT_MATH NUMBER,
   STUDENT_ENG NUMBER,
   STUDENT_KOR NUMBER,
   STUDENT_GRADE VARCHAR2(1000)
   );