CREATE TABLE movies (
  id NUMBER(10) PRIMARY KEY,
  title VARCHAR2(255) NOT NULL,
  director VARCHAR2(255),
  genre VARCHAR2(255),
  release_year NUMBER(4)
);

CREATE SEQUENCE movies_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE movies MODIFY (id DEFAULT HR.MOVIES_SEQ.NEXTVAL);