CREATE TABLE tbl_user(
	USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_PHONE VARCHAR2(500) NOT NULL,
	USER_NICKNAME VARCHAR2(500),
	USER_EMAIL VARCHAR2(500) NOT NULL,
	USER_ADDRESS VARCHAR2(500),
	USER_BIRTH DATE,
	USER_RECOMMENDER_ID VARCHAR2(500)
);

DROP TABLE TBL_USER;

SELECT * FROM TBL_USER;

-- 사용자 정보를 저장하는 유저 테이블 생성하기
CREATE SEQUENCE seq_user;

-- TBL_USER1
-- 사용자 번호 USER1_NUMBER
-- 사용자 아이디 USER1_ID
-- 패스워드 USER1_PASSWORD
-- 이름 USER1_NAME
-- 나이 USER1_AGE
-- 성별 USER1_GENDER CHAR(1) DEFAULT 'N',
-- 생일 USER1_BIRTH DATE, CONSTRANINT PK_USER PRIMARY KEY(USER1_NUMBER)

CREATE TABLE TBL_USER1(
USER1_NUMBER NUMBER,
USER1_ID VARCHAR(1000),
USER1_PASSWORD VARCHAR(1000),
USER1_NAME VARCHAR(1000),
USER1_AGE NUMBER,
USER1_GENDER CHAR(1) DEFAULT 'N',
USER1_BIRTH DATE,
CONSTRAINT PK_USER1 PRIMARY KEY(USER1_NUMBER)
);
CREATE SEQUENCE seq_user;

SELECT USER1_NUMBER FROM TBL_USER1;
SELECT * FROM TBL_USER1;

-- 데이터 삽입
INSERT INTO tbl_user1 values(seq_user.nextval, 'aaa', '1234', '홍길동', 22, 'M', '20000101');

INSERT INTO tbl_user1 (USER1_NUMBER, USER1_ID, USER1_PASSWORD, USER1_NAME, USER1_AGE, USER1_BIRTH)
VALUES(SEQ_USER.NEXTVAL, 'bbb', '1234', '성춘향', 24, '2001-01-02');

INSERT INTO TBL_USER1 (USER1_NUMBER, USER1_ID, USER1_PASSWORD, USER1_NAME, USER1_AGE, USER1_BIRTH)
VALUES(SEQ_USER.NEXTVAL, 'ccc', '1234', '김철수', 35, TO_DATE('1988-11-02', 'YYYY-MM-DD'));

SELECT * FROM TBL_USER1 tu;

-- 테이블에 행 6개만 남기기
DELETE FROM TBL_USER1
WHERE USER1_NUMBER = ;


INSERT INTO tbl_user(USER_ID,USER_IDENTIFICATION,USER_PASSWORD,USER_NAME,USER_PHONE,USER_NICKNAME,USER_EMAIL,USER_BIRTH) values(123, 'a1', '1234', '김영선', '01012345678', '별', 'abc@naver.com','20000101');

CREATE TABLE tbl_user(
	USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_PHONE VARCHAR2(500) NOT NULL,
	USER_NICKNAME VARCHAR2(500),
	USER_EMAIL VARCHAR2(500) NOT NULL,
	USER_ADDRESS VARCHAR2(500),
	USER_BIRTH DATE,
	USER_RECOMMENDER_ID VARCHAR2(500)
);
SELECT * FROM TBL_USER;




