
CREATE SEQUENCE SEQ_USERT;

CREATE TABLE tbl_user(
	USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_PHONE VARCHAR2(500) NOT NULL,
	USER_NICKNAME VARCHAR2(500),
	USER_EMAIL VARCHAR2(500) NOT NULL,
	USER_ADDRESS VARCHAR2(500),
	USER_BIRTH DATE,
	USER_RECOMMENDER_ID VARCHAR2(500)
);
SELECT * FROM TBL_USER;

